# Docker Compose override for development
# This file is automatically loaded by docker-compose
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  notesapp:
    volumes:
      # Mount source code for live reloading during development
      - .:/app
      # Still mount the data volume for persistent database
      - notes_data:/app/data
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    # Override the default command to run in debug mode
    command: ["python", "notes.py", "server", "--host", "0.0.0.0", "--port", "5000", "--debug"]
